// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iswutidxywbmstfgbrag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzd3V0aWR4eXdibXN0ZmdicmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzI1NzAsImV4cCI6MjA3MTE0ODU3MH0.GUyATIsbFh9e1YxPN3f5qhqrVeDDzhXMfMLPTOY2ck4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});